---

version: "3.6"
services:
  db:
    image: "postgres:9.6.9-alpine"
    user: "${UID}:${GID}"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    networks:
      - webnet

  web:
    <<: &web
      # Image for production:
      image: "registry.gitlab.com/ffedoroff/ticket:latest"
      user: "${UID}:${GID}"
      restart: unless-stopped
      ports:
        - "25004:5004"
      networks:
        - webnet
      depends_on:
        - db
      environment:
        DJANGO_DATABASE_HOST: db
    command: sh ./docker/django/uwsgi.sh

networks:
  # Network for your internals, use it by default:
  webnet:

# docker-compose -f docker-compose.prod.yml up -d
# docker-compose -f docker-compose.prod.yml run --rm web python manage.py migrate
