# Generated by Django 2.2.12 on 2020-04-17 14:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import server.json_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(help_text='source: id', max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='source: name', max_length=240)),
                ('start_date', models.DateTimeField(help_text='source: dates.start.dateTime')),
                ('promoter_name', models.CharField(help_text='source: promoter.name', max_length=240)),
                ('cost_min', models.DecimalField(decimal_places=2, help_text='source: priceRanges.min', max_digits=10)),
                ('cost_max', models.DecimalField(decimal_places=2, help_text='source: priceRanges.max', max_digits=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=server.json_tools.DecimalJSONEncoder, help_text='raw json data')),
            ],
        ),
    ]
