# Generated by Django 2.2.12 on 2020-04-16 11:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import server.json_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(help_text='source: id', max_length=120, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=server.json_tools.DecimalJSONEncoder, help_text='raw json data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
