---

version: "3.6"
services:
  db:
    image: "postgres:9.6.9-alpine"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    networks:
      - webnet

  web:
    <<: &web
      # Image for production:
      image: "registry.gitlab.com/ffedoroff/ticket:latest"
      build:
        target: production_build
        args:
          DJANGO_ENV: production
        context: ./
      restart: unless-stopped
      ports:
        - "25004:5004"
      networks:
        - webnet
      depends_on:
        - db
      environment:
        DJANGO_DATABASE_HOST: db
        DJANGO_ENV: production
    volumes:
      - django-locale:locale:rw
      - django-media:/var/www/django/media:rw
      - django-static:/var/www/django/static:rw
    command: sh ./docker/django/uwsgi.sh

networks:
  # Network for your internals, use it by default:
  webnet:

volumes:
  pgdata:
  django-static:
  django-media:
  django-locale:

# docker-compose up -d
# docker-compose run --rm db psql -h db -U postgres
# docker-compose run --rm web python manage.py migrate
# docker-compose run --rm web python manage.py createsuperuser
